fix(server): no min police for safe
Qbox-project/qb-storerobbery pull request #8
Opened 2023-06-19 19:00 UTC by buddizer

## Description

Just a small fix so that it doesn't get overlooked in the future. 

## Checklist

- [x] I have personally loaded this code into an updated Qbox project and checked all of its functionality.
- [x] My code fits the style guidelines.
- [x] My PR fits the contribution guidelines.

2023-06-19 19:03 UTC, BerkieBb commented
A little indentation can't do any harm 😄

2023-06-19 19:10 UTC, buddizer commented
You mean using enters for this line? I thought I was identing with the 4 spaces 😝 , just went ahead and copied the line from the registers one just for a quick fix since I've noticed people abusing this already, with that said I am thinking on porting to lib zones and so on and submitting a proper PR 😁

2023-06-19 20:13 UTC, Manason requested changes

2023-06-19 20:13 UTC, Manason commented on server.lua
> +    if Amount < Config.MinimumCops then if Config.NotEnoughCopsNotify then QBCore.Functions.Notify(PlayerSource, Lang:t('error.no_police', { Required = Config.MinimumCops }), 'error') end return end
```suggestion
    if Amount < Config.MinimumCops and Config.NotEnoughCopsNotify then    
        QBCore.Functions.Notify(PlayerSource, Lang:t('error.no_police', { 
            Required = Config.MinimumCops
        }), 'error')
    return
    end
```

2023-06-19 20:21 UTC, buddizer commented
Done

2023-06-19 23:16 UTC, Manason approved these changes

2023-06-20 14:34 UTC, ChatDisabled commented
> since I've noticed people abusing this already

Wow already being used in production

2023-06-20 14:34 UTC, merged

2023-06-20 17:07 UTC, buddizer commented
> > since I've noticed people abusing this already
> 
> Wow already being used in production

Wait till they find out a wipe is coming once it is all ready